name: Test Workflow

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run formatter
        uses: psf/black@stable
      - name: Step 1
        run: echo step 1
      - name: Step 2
        run: echo step 2
      - name: Step 3
        run: echo step 3
